# Generated by Django 5.2.10 on 2026-01-10 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Certification name (e.g., "8(a) Certified")',
                        max_length=200,
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True, help_text='Short form (e.g., "WOSB")', max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the certification"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Certification logo/badge",
                        null=True,
                        upload_to="certifications/",
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True, help_text="Certification ID number", max_length=100
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for display (lower numbers first)"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show prominently on homepage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OfficeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Location name (e.g., "Minneapolis Office")',
                        max_length=200,
                    ),
                ),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="United States", max_length=100)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Mark as primary location"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for display (lower numbers first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Office Location",
                "verbose_name_plural": "Office Locations",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Setting key (e.g., company_phone)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(help_text="Setting value")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this setting is used for"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
                "ordering": ["key"],
            },
        ),
    ]
