# Generated by Django 5.2.10 on 2026-01-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapabilityDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("general", "General Capability Statement"),
                            ("federal", "Federal Capability Statement"),
                            ("international", "International Capability Statement"),
                        ],
                        default="general",
                        help_text="Type of capability statement downloaded",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of downloader", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent string", max_length=500
                    ),
                ),
                (
                    "referer",
                    models.URLField(blank=True, help_text="Referring page URL"),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Capability Download",
                "verbose_name_plural": "Capability Downloads",
                "ordering": ["-downloaded_at"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "downloaded_at"],
                        name="contact_cap_documen_453bf5_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "downloaded_at"],
                        name="contact_cap_ip_addr_1edf3b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Contact name", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization name (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering & Energy Systems"),
                            ("data_science", "Data Science & Analytics"),
                            ("research", "Research & Strategic Analysis"),
                            ("international", "International Development"),
                            ("capacity_building", "Capacity Building & Training"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of project or service needed",
                        max_length=50,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Project details or inquiry message"),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_50k", "Under $50,000"),
                            ("50k_100k", "$50,000 - $100,000"),
                            ("100k_250k", "$100,000 - $250,000"),
                            ("250k_500k", "$250,000 - $500,000"),
                            ("500k_1m", "$500,000 - $1,000,000"),
                            ("over_1m", "Over $1,000,000"),
                            ("not_specified", "Not Specified"),
                        ],
                        default="not_specified",
                        help_text="Estimated budget range (optional)",
                        max_length=50,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether submission has been reviewed"
                    ),
                ),
                (
                    "is_responded",
                    models.BooleanField(
                        default=False, help_text="Whether response has been sent"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this submission"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of submitter (for spam detection)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User agent string (for spam detection)",
                        max_length=500,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "submitted_at"],
                        name="contact_con_is_read_e1b731_idx",
                    ),
                    models.Index(
                        fields=["is_responded", "submitted_at"],
                        name="contact_con_is_resp_5e0252_idx",
                    ),
                    models.Index(
                        fields=["project_type", "submitted_at"],
                        name="contact_con_project_d0db79_idx",
                    ),
                ],
            },
        ),
    ]
