# Generated by Django 5.2.10 on 2026-01-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Service name (e.g., "Data Science & Analytics")',
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of title",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief description for cards and listings (max 500 characters)",
                        max_length=500,
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        help_text="Full description for service detail page"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="chart-bar",
                        help_text='Heroicon name (e.g., "chart-bar", "lightning-bolt", "globe-alt")',
                        max_length=50,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image for service page",
                        null=True,
                        upload_to="services/",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for display (lower numbers appear first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this service is currently offered",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show prominently on homepage"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (defaults to title if not set)",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description (defaults to short_description if not set)",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="services_se_slug_f039d2_idx"
                    ),
                    models.Index(
                        fields=["display_order", "is_featured"],
                        name="services_se_display_206ca4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Feature title", max_length=200)),
                ("description", models.TextField(help_text="Feature description")),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Optional icon name", max_length=50
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Feature",
                "verbose_name_plural": "Service Features",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_study_id",
                    models.IntegerField(help_text="ID of related case study"),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_case_studies",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Case Study",
                "verbose_name_plural": "Service Case Studies",
                "ordering": ["display_order"],
                "unique_together": {("service", "case_study_id")},
            },
        ),
    ]
