# Generated by Django 5.2.10 on 2026-01-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Post title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of title",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("author", models.CharField(help_text="Author name", max_length=100)),
                (
                    "author_bio",
                    models.TextField(blank=True, help_text="Brief author biography"),
                ),
                (
                    "author_email",
                    models.EmailField(
                        blank=True, help_text="Author email (optional)", max_length=254
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short excerpt for listings and previews (max 500 characters)",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full post content (supports markdown or HTML)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering"),
                            ("data_science", "Data Science"),
                            ("climate", "Climate & Sustainability"),
                            ("government", "Government Contracting"),
                            ("international", "International Development"),
                            ("general", "General"),
                        ],
                        default="general",
                        help_text="Post category",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated tags (e.g., "renewable energy, climate, Kenya")',
                        max_length=500,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image for post",
                        null=True,
                        upload_to="blog/",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Make visible on public site"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show prominently on homepage or blog list",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        help_text="Date and time to publish (used for scheduling)"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (defaults to title if not set)",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description (defaults to excerpt if not set)",
                        max_length=300,
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, help_text="Number of times post has been viewed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_published"],
                        name="blog_blogpo_slug_c2a5f8_idx",
                    ),
                    models.Index(
                        fields=["category", "is_published"],
                        name="blog_blogpo_categor_9cf0b8_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "is_published"],
                        name="blog_blogpo_is_feat_c93357_idx",
                    ),
                    models.Index(
                        fields=["published_date", "is_published"],
                        name="blog_blogpo_publish_9f282d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog/images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility",
                        max_length=200,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Image",
                "verbose_name_plural": "Blog Images",
                "ordering": ["display_order"],
            },
        ),
    ]
