# Generated by Django 5.2.10 on 2026-01-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Project title (e.g., "Hybrid Solar-Biomass Mango Drier")',
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of title",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("federal", "Federal Agency"),
                            ("state", "State/Local Government"),
                            ("international", "International Organization"),
                            ("corporate", "Corporate"),
                            ("foundation", "Foundation/NGO"),
                            ("other", "Other"),
                        ],
                        help_text="Type of client organization",
                        max_length=50,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="Client name (optional, may be confidential)",
                        max_length=200,
                    ),
                ),
                (
                    "challenge",
                    models.TextField(
                        help_text="Problem statement or challenge addressed"
                    ),
                ),
                (
                    "solution",
                    models.TextField(help_text="Approach and solution implemented"),
                ),
                ("results", models.TextField(help_text="Results and impact achieved")),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Technologies, tools, or methodologies used (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "impact_metrics",
                    models.JSONField(
                        blank=True,
                        help_text='Key metrics as JSON (e.g., {"energy_saved": "45%", "cost_reduction": "$50k"})',
                        null=True,
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        help_text="Main featured image for case study",
                        upload_to="case_studies/",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Show prominently on homepage"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, help_text="Make visible on public site"
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        help_text="Date project was completed or published"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (defaults to title if not set)",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, help_text="SEO description", max_length=300
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary service category for this project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_case_studies",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Study",
                "verbose_name_plural": "Case Studies",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseStudyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="case_studies/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility (auto-generated if blank)",
                        max_length=200,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Use as primary image if hero_image is not set",
                    ),
                ),
                (
                    "case_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.casestudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Study Image",
                "verbose_name_plural": "Case Study Images",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="CaseStudyTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(help_text="Testimonial text")),
                (
                    "author_name",
                    models.CharField(
                        help_text="Testimonial author name", max_length=200
                    ),
                ),
                (
                    "author_title",
                    models.CharField(
                        blank=True, help_text="Author job title or role", max_length=200
                    ),
                ),
                (
                    "author_organization",
                    models.CharField(
                        blank=True, help_text="Author organization", max_length=200
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "case_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="portfolio.casestudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Study Testimonial",
                "verbose_name_plural": "Case Study Testimonials",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="casestudy",
            index=models.Index(
                fields=["slug", "published"], name="portfolio_c_slug_391a68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casestudy",
            index=models.Index(
                fields=["featured", "published"], name="portfolio_c_feature_220d1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casestudy",
            index=models.Index(
                fields=["client_type", "published"],
                name="portfolio_c_client__a73fd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casestudy",
            index=models.Index(
                fields=["service", "published"], name="portfolio_c_service_94a8c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casestudyimage",
            index=models.Index(
                fields=["case_study", "display_order"],
                name="portfolio_c_case_st_b47886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casestudytestimonial",
            index=models.Index(
                fields=["case_study", "display_order"],
                name="portfolio_c_case_st_6557ca_idx",
            ),
        ),
    ]
